---
deployment:
  tasks:
    - export DEPLOYPATH=/home/samgunof/node/kpop_database/
    - /bin/cp -R src $DEPLOYPATH
    - /bin/cp .gitattributes $DEPLOYPATH
    - /bin/cp .gitignore $DEPLOYPATH
    - /bin/cp .sequelizerc $DEPLOYPATH
    - /bin/cp index.js $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - /bin/cp README.md $DEPLOYPATH
