module.exports = {
	artistSeeder: [
		{
			id: 1,
			stage_name: "Red Velvet",
			korean_name: "레드벨벳",
			profile_desc: `Red Velvet is a charming 5-member girl group born to attract the world through their unique and sophisticated music and performances. With members IRENE, SEULGI, WENDY, JOY, and YERI, Red Velvet has become one of Korea’s (and the world’s) biggest girl groups, known for their versatile talents and charms. Red Velvet debuted with their 1st single ‘Happiness’ in August 2014. Their following albums ‘Ice Cream Cake’, ‘The Red’, ‘The Velvet’, and ‘Russian Roulette’ have all charted in the top spots in Korea immediately upon release. In 2017, ‘Rookie’, ‘The Red Summer’, and ‘Perfect Velvet’ all achieved No. 1 on Billboard’s World Albums chart, earning Red Velvet the top girl group status. ‘Bad Boy’, the lead single from ‘The Perfect Red Velvet’ album, debuted at No. 3 on Billboard’s World Albums chart and earned them their best U.S. sales to date. Red Velvet’s title track ‘Psycho’ from ‘The ReVe Festival: Finale’ album charted No. 1 on Billboard’s World Digital Song Sales chart after release in December 2019. The group set record as the first female K-pop act to top iTunes Top Albums chart in 44 countries with ‘The ReVe Festival: Finale'. In August 2021, Red Velvet released their long-awaited 6th EP, ‘Queendom’ once again proving their global popularity as “Summer Queens” topping Korean and international music charts, most notably iTunes Top Albums chart in 51 countries around the world.`,
			debut_year: 2014,
			career_type: "Group",
			active_status: true,
			created_at: new Date(),
			updated_at: new Date(),
			deleted_at: null,
		},
		{
			id: 2,
			stage_name: "TWICE",
			korean_name: "트와이스",
			profile_desc: `TWICE is a K-Pop girl group produced by JYP Entertainment through the reality program [SIXTEEN]. The group is composed of 9 members: NAYEON, JEONGYEON, MOMO, SANA, JIHYO, MINA, DAHYUN, CHAEYOUNG, and TZUYU. Debuted on October 20th, 2015 with the 1st EP [THE STORY BEGINS] that featured the title track “Like OOH-AHH”, the group then achieved bigger fame in 2016 with the 2nd EP [PAGE TWO] that featured “CHEER UP.” Since then, the group has won several big awards with TWICE’s own music style 'color pop' and continued to release the unique bright, energetic and catchy songs: “TT”, “KNOCK KNOCK”, “SIGNAL”, “LIKEY”, “Heart Shaker”, "What is Love?", "Dance The Night Away", "YES or YES" ,"The Best Thing I Ever Did", "FANCY", "Feel Special", "MORE & MORE" ,"I CAN'T STOP ME", "Alcohol-Free", "The Feels", and "SCIENTIST". Given the title of 'one Top girl group' in Asia, TWICE is growing with a meaningful expansion of more global presence. <3`,
			debut_year: 2015,
			career_type: "Group",
			active_status: true,
			created_at: new Date(),
			updated_at: new Date(),
			deleted_at: null,
		},
		{
			id: 3,
			stage_name: "aespa",
			korean_name: "에스파",
			profile_desc: `aespa, a combination of “ae”, which stands for “Avatar and Experience” and “aspect” meaning “two-sidedness”, symbolizes “meeting of another self and experiencing a new world” and consists of four real members KARINA, WINTER, GISELLE, and NINGNING along with avatar members of each. The group debuted in November 2020 with a single ‘Black Mamba’. The song entered the Billboard Global Chart (excluding U.S.) at No. 100 within just 3 days, marking the highest ranking of any K-pop artist’s debut song. It charted across music charts in 95 countries, proving their explosive popularity immediately upon debut. aespa set monumental records with ‘Black Mamba’ surpassing 21 million views in the first 24 hours of its release, and became the fastest debut MV to surpass 100 million views in the history of K-pop, setting another new record. In May, aespa released a single ‘Next Level’, which received enthusiastic response immediately upon release. The MV surpassed 50 million views in just 3 days, breaking self-record. It debuted at No. 1 on Korean and international music charts in addition to reaching No. 3 on Billboard’s World Digital Song Sales chart, scoring another worldwide hit. Following their 2nd Mini Album "Girls", aespa released their 3nd Mini Album "MY WORLD" on May 8th, 2023.`,
			debut_year: 2020,
			career_type: "Group",
			active_status: true,
			created_at: new Date(),
			updated_at: new Date(),
			deleted_at: null,
		},
		{
			id: 4,
			stage_name: "NewJeans",
			korean_name: "뉴진스",
			profile_desc: `NewJeans (MINJI, HANNI, DANIELLE, HAERIN, and HYEIN) are the first group to debut on July 22, 2022, from ADOR, an independent label under HYBE led by Min Hee Jin. The quintet aspires to push the limits of K-pop with honest and authentic music that exudes youth. Just like a pair of jeans that has been a staple of every wardrobe for generations, NewJeans aim to allure the listeners with timeless music to be kept in your daily music playlist. The act released New Jeans on August 1, 2022, instantly captivating the global audience and becoming the first K-pop band to achieve the million-seller milestone with their debut album. “Hype Boy,” one of the triple title tracks from their debut album, charted on Billboard Global 200 for 32 consecutive weeks - the longest record from any K-pop female act. NewJeans continue to amaze the world with groundbreaking records while staying true to their musical flair and intrinsic charm, recently making their Billboard Hot 100 debut — within less than half a year of their debut — with global smash hits “Ditto” and “OMG.”`,
			debut_year: 2022,
			career_type: "Group",
			active_status: true,
			created_at: new Date(),
			updated_at: new Date(),
			deleted_at: null,
		},
		{
			id: 5,
			stage_name: "Dreamcatcher",
			korean_name: "드림캐쳐",
			profile_desc: `A South Korean girl group who fuse mysterious horror and fantasy themes with slick dance-pop, rock, and metal, Dreamcatcher rose quickly into the K-pop mainstream with a series of loosely thematic EPs in 2017 and 2018. A breakout act at home, the seven-member group also found a more widespread international audience which they fostered over the next two years with tours of Europe, Asia, and South America. Their largest audience outside of South Korea emerged in Japan where they released the 2019 full-length album, The Beginning of the End. They have continued to hit the Top Five in Korea with albums like 2020's Dystopia: The Tree of Language and 2022's Apocalypse: Save Us. Formed in 2014 by Happy Face Entertainment, the initial lineup of Jiu, Sua, Siyeon, Yoohyeon, and Dami released a handful of singles and the 2015 EP, Love Shake, under the name Minx. As Minx, the group's songs trended toward a bright, bubbly K-pop style with a decidedly cheerful youth-oriented aesthetic. They enjoyed moderate success during this early phase, but by the end of 2016, Happy Face announced that Minx had taken on two new members, Handong and Gahyeon, and would soon reemerge in a darker-toned version under the name Dreamcatcher. Distancing themselves from the wholesome image of their early days, the seven-member Dreamcatcher fused adult-oriented dance music with elements of rock and metal. Their edgy new sound and look was further enhanced by the use of horror and fantasy themes which they quickly established on singles like "Nightmare" and "Chase Me." Released in July 2017, Dreamcatcher's first EP, Prequel, quickly found an audience at home while also charting in Japan and on the U.S. Billboard World Albums chart. One of the year's breakout K-pop acts, the group entered 2018 with another horror-themed hit, "Full Moon," and a major tour of Europe to nurture their growing international fan base. Following the May release of their second EP, Escape the Era, Dreamcatcher traveled to South America for their Welcome to the Dream World in Latin America. They ended their banner year with a third EP, Alone in the City, which hit number two on the Korean chart, making it their highest placement yet. Appearing in February 2019, The End of Nightmare EP marked the final entry in the thematic arc that began with their debut single, "Nightmare." It's lead single, "Piri," mixed their trademark rock sounds with the double-reeded Korean instrument, the piri. A major tour of Asia and Oceania acted as a build-up to the September release of The Beginning of the End, Dreamcatcher's first Japanese full-length album. Around this time the group launched their highly anticipated official fan club, Insomnia, which was open to both South Korean and Japanese fans. Their Korean comeback EP, Raid of Dream, arrived a mere week after the Japanese album, led by the single "Deja Vu," a song written for the King's Raid mobile game. Dreamcatcher ended the year (and decade) on a high note with another large-scale tour of Europe. In January 2020, the group returned with their debut Korean full-length album, Dystopia: The Tree of Language. Buoyed by the singles "Paradise" and "Scream," the album reached number 3 on the Goan album chart. It was followed by two companion EPs, 2020's Dystopia: Lose Myself and 2021's Dystopia: Road to Utopia, the latter of which topped the Korean albums chart. Also in 2021, they released the special Korean EP Summer Holiday. Dreamcatcher's second Korean full-length, Apocalypse: Save Us, arrived in April 2022, hitting number four on the Gaon chart.`,
			debut_year: 2014,
			career_type: "Group",
			active_status: true,
			created_at: new Date(),
			updated_at: new Date(),
			deleted_at: null,
		},
		{
			id: 6,
			stage_name: "IVE",
			korean_name: "아이브",
			profile_desc: `South Korea's Ive is an all-girl pop outfit known for their hooky, dance-oriented sound. The group debuted to major success, topping the Goan charts with 2021's "Eleven" and 2022's "Love Dive." A third single, "After Like," followed in 2022. Formed in 2021 by the Seoul-based Starship Entertainment, Ive features the talents of Yujin, Gaeul, Rei, Wonyoung, Liz, and Leeseo. Prior to joining the group, both Wonyoung and Yujin had competed in the Produce 48 talent contest and were members of the group Iz*One until it broke up in 2021. Ive (a stylized spelling of the contraction "I've" or "I have"), made their debut in December 2021 with the single "Eleven," which topped the Korean Gaon Album chart. It also reached the Top Ten of Billboard's World Digital Songs Sales chart and cracked the Japan Hot 100. A second single, "Love Dive," arrived in April 2022, also hitting number one in Korea. The group returned that August with their third single, "After Like".`,
			debut_year: 2021,
			career_type: "Group",
			active_status: true,
			created_at: new Date(),
			updated_at: new Date(),
			deleted_at: null,
		},
		{
			id: 7,
			stage_name: "Le Sserafim",
			korean_name: "르세라핌",
			profile_desc: `LE SSERAFIM is a girl group with SOURCE MUSIC, a label under HYBE, consisting of five members of different nationalities: SAKURA, KIM CHAEWON, HUH YUNJIN, KAZUHA and HONG EUNCHAE. The first girl group to launch through a collaboration between HYBE and SOURCE MUSIC, they are taking a daring stance and saying right from the outset that they will stand at the very top. The group’s name, LE SSERAFIM, is an anagram of the words “I’M FEARLESS.” The name captures the group’s self-confidence and iron will as they go out into the world fearlessly and unwavering before the watchful eyes of the world. It is like an incantation to guarantee their success on the merit of their unbreakable poise and strength.`,
			debut_year: 2022,
			career_type: "Group",
			active_status: true,
			created_at: new Date(),
			updated_at: new Date(),
			deleted_at: null,
		},
		{
			id: 8,
			stage_name: "IU",
			korean_name: "아이유",
			profile_desc: `South Korean singer, songwriter, and actress Lee Ji-eun performs on the sweeter side of the K-pop spectrum, often focused on ballads and light pop. Choosing the stage name IU -- derived from "I" and "you" to symbolize unity -- Lee debuted in the late 2000s with early efforts Lost &amp; Found and IU...IM, but had her breakthrough in 2010 with the chart-topping "Good Day" from her third EP, Real. She remained a fixture at the top of the Korean charts into the 2020s with hits such as 2011's Last Fantasy, 2019's Love Poem, and 2021's platinum-certified Lilac. In addition to her success in Korea, she also branched out into the Japanese market and, in 2020, scored her first number one in the U.S. with "Eight." Born in Seoul, she began her journey in the entertainment industry at a very young age, enrolling in acting classes while still in elementary school. By middle school, she'd developed a love for singing and trained with Good Entertainment (Shinhwa) before signing with LOEN Entertainment in 2007. With a girl-next-door image, Lee made her 2008 debut with the Lost &amp; Found EP, which featured the single "Lost Child." The following year, Lee issued her first full-length, Growing Up, which featured the dance-oriented single "Boo." Months later, the EP IU...IM arrived, including the effervescent singles "Love Attack" and "Marshmallow." It wasn't until the end of 2010 and her third EP, Real, that the singer experienced her commercial breakthrough. Her highest-charting effort to date, Real debuted a more mature sound for the singer. Featuring the "Good Day" single, it was quickly followed by the three-song expansion single Real+. Her sophomore set, Last Fantasy, was issued in 2011. Her highest-selling album, it was also her first chart-topper in Korea, and the track "You and I" spent five weeks atop the Billboard K-Pop Hot 100. Eventually, Last Fantasy would win Record of the Year at the Seoul Music Awards and become the 15th best-selling Korean album of the year. Following the success of Fantasy, Lee inked a deal with EMI Music Japan, which broke her into the Japanese market in 2013 with the Can You Hear Me? EP, which was her first Japanese-language effort. Recorded in Japan, Korea, China, and the United States, the five-song collection also featured production by Jimmy Jam and Terry Lewis. That same year, Lee released her third LP, Modern Times, which continued her sonic maturity with hints of jazz and bossa nova. In 2014, her sixth EP, A Flower Bookmark, was released. The collection comprised covers of popular Korean pop songs from the '80s and '90s, like Kim Wan-sun's 1990 song "Pierrot Smiles at Us" and Jo Deok-bae's 1985 "My Old Story." That summer, Lee made her first American concert appearance at KCON in Los Angeles. By 2015, she'd made her debut as sole lyricist and producer on her seventh EP, Chat-Shire, which peaked at number four on the Billboard World Albums chart. As her acting roles continued to maintain her visibility throughout East Asia, Lee issued her fourth LP, the critically acclaimed Palette, in 2017. Debuting atop the Korean Gaon chart and the Billboard World Albums chart, Palette featured Big Bang's G-Dragon on the title track. A sequel EP, A Flower Bookmark 2, landed later that year. IU spent 2018 playing a prominent role on the television show My Mister. She also celebrated the tenth anniversary of her debut by issuing the single "Bbibbi." She continued acting into 2019 with Persona and Hotel del Luna while also releasing her ninth EP, the chart-topping Love Poem, that November. 2020 saw the arrival of the Suga-produced single "Eight," which became her first U.S. number one. In March 2021, she returned with her fifth full-length album, Lilac. Buoyed by the single "Celebrity," the album topped the South Korean charts and was certified platinum.`,
			debut_year: 2008,
			career_type: "Soloist",
			active_status: true,
			created_at: new Date(),
			updated_at: new Date(),
			deleted_at: null,
		},
		{
			id: 9,
			stage_name: "KARA",
			korean_name: "카라",
			profile_desc: `KARA was a popular South Korean girl group formed by DSP Media. The group debuted in 2007 and originally consisted of four members: Gyuri, Seungyeon, Hara, and Nicole. KARA gained significant success both domestically and internationally with their catchy pop songs and synchronized dance routines. They were known for their bright and energetic image, captivating fans with their charming personalities. KARA released several hit songs, including "Mister," "Step," and "Lupin," which solidified their position as one of the top girl groups in the K-pop industry. Although the group disbanded in 2016, KARA left a lasting impact on the K-pop scene.`,
			debut_year: 2007,
			career_type: "Group",
			active_status: false,
			created_at: new Date(),
			updated_at: new Date(),
			deleted_at: null,
		},
		{
			id: 10,
			stage_name: "ITZY",
			korean_name: "있지",
			profile_desc: `South Korean quintet Itzy put an energetic spin on K-pop, serving buoyant electronic dance anthems with uplifting lyrics. Debuting at the close of the 2010s, they released their Top Three EP It'z Icy in July 2019, followed by March 2020's It'z Me. More Top Five sets appeared, including 2020's Not Shy and 2021's Guess Who. In late 2021, the band released their first full-length, the chart-topping Crazy in Love. The following year, they hit a U.S. chart peak with their Top Ten EP Checkmate. Joining TWICE on JYP Entertainment's girl group roster, Itzy is comprised of Yeji, Lia, Ryujin, Chaeryeong, and Yuna. Through the mid-2010s, most group members competed on various television survival shows before JYP put them together as the five-piece Itzy. They debuted in January 2019 and issued their first single, "Dalla Dalla" b/w "Want It?" These hit tracks appeared on their summertime debut EP, It'z Icy, which rose to the Top Three in Korea and placed within the Top 20 on both the U.S. Heatseekers and World Albums charts. The propulsive lead single "Icy" peaked at number two on the Billboard World Songs chart. Their follow-up EP, It'z Me, appeared in March 2020 and topped the Korean pop chart, as did their third outing, Not Shy, which arrived in August. Another Top Five Korean EP, Guess Who, was released in 2021. The short set was Itzy's first appearance on the main Billboard 200 chart. Months later, they bested that showing with their much-anticipated full-length debut, Crazy in Love, which peaked just outside the U.S. Top Ten. The "Loco"-featuring set also topped the Billboard World Albums and Independent Albums charts, while rising to number two in Korea. A non-album single, the Japanese-language "Voltage," arrived in April 2022. Months later, they landed in the U.S. Top Ten for the first time with their fifth EP, Checkmate, which featured the single "Sneakers." The group closed the year with a sixth EP, Cheshire.`,
			debut_year: 2019,
			career_type: "Group",
			active_status: true,
			created_at: new Date(),
			updated_at: new Date(),
			deleted_at: null,
		},
		{
			id: 11,
			stage_name: "NMIXX",
			korean_name: "엔믹스",
			profile_desc: `NMIXX is a South Korean girl groups formed by SQU4D, a sub-label of JYP Entertainment. Consisting of LILY, HAEWON, SULLYOON, BAE, JIWOO and KYUJIN, NMIXX debuted in February 2022 with the single AD MARE that featured the title track "O.O". The name NMIXX combines the letter "N", which stands for "now", "new", "next" and the unknown "n", and the word "mix", which symbolizes combination and diversity, altogether meaning "the best combination for a new era". NMIXX’s debut single AD MARE introduces a new genre called MIXX POP, packed with the confidence and ambition of a new group ready to take on the world. It blends in two or more genres into one flavorful song and represents the unusual experiment of NMIXX. “O.O” is a reinterpretation of baile funk and the track leads the listeners to the world of MIXX POP. After the start of promotions the MV of "O.O" surpassed 20 million views in the first 24 hours of its release. The song entered the Billboard Global Chart (excluding U.S.) at No. 71, and also ranked No. 138 on Billboard Global 200. Meanwhile AD MARE sold over 220K copies in the first week, recorded the highest debut album sales by a girl group ever in K-pop history.`,
			debut_year: 2022,
			career_type: "Group",
			active_status: true,
			created_at: new Date(),
			updated_at: new Date(),
			deleted_at: null,
		},
	],
};
